// List of Pakistani cities - Same across the application
export const PAKISTANI_CITIES = [
  "Islamabad",
  "Rawalpindi",
  "Lahore",
  "Karachi",
  "Peshawar",
  "Faisalabad",
  "Multan",
  "Gujranwala",
  "Hyderabad",
  "Quetta",
  "Sialkot",
  "Bahawalpur",
  "Sukkur",
  "Larkana",
  "Kohat",
  "Dera Ghazi Khan",
  "Abbottabad",
  "Muzaffarabad",
  "Gilgit",
  "Skardu",
  "Mardan",
  "Nowshera",
  "Chakwal",
  "Jhelum",
  "Sargodha",
  "Mianwali",
  "Bhakkar",
  "Layyah",
  "Khushab",
  "Toba Tek Singh",
  "Gujrat",
  "Mandi Bahauddin",
  "Hafizabad",
  "Narowal",
  "Kasur",
  "Okara",
  "Pakpattan",
  "Vehari",
  "Lodhran",
  "Khanewal",
  "Bahawalnagar",
  "Rahim Yar Khan",
  "Sanghar",
  "Mirpur Khas",
  "Nawabshah",
  "Khairpur",
  "Shikarpur",
  "Jacobabad",
  "Dadu",
  "Thatta",
  "Badin",
  "Attock",
  "Murree",
  "Campbellpur",
  "Talagang",
  "Hazara",
];
